# Generated by Django 4.2.15 on 2024-10-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
